In [1]:
import pandas as pd
import numpy as np
from pandas_datareader import data
import yfinance as yf

In [2]:
spy=data.get_data_yahoo("SPY", start="2000-01-01")

In [3]:
msft=yf.Ticker("MSFT")

In [4]:
hist=msft.history(period="max")

In [5]:
msft_p=pd.DataFrame(hist)

In [6]:
msft_p

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13,0.055898,0.064119,0.055898,0.061378,1031788800,0.0,0.0
1986-03-14,0.061378,0.064667,0.061378,0.063570,308160000,0.0,0.0
1986-03-17,0.063570,0.065215,0.063570,0.064667,133171200,0.0,0.0
1986-03-18,0.064667,0.065215,0.062474,0.063022,67766400,0.0,0.0
1986-03-19,0.063022,0.063570,0.061378,0.061926,47894400,0.0,0.0
...,...,...,...,...,...,...,...
2021-12-23,332.750000,336.390015,332.730011,334.690002,19611200,0.0,0.0
2021-12-27,335.459991,342.480011,335.429993,342.450012,19947000,0.0,0.0
2021-12-28,343.149994,343.809998,340.320007,341.250000,15661500,0.0,0.0
2021-12-29,341.299988,344.299988,339.679993,341.950012,15027300,0.0,0.0
2021-12-30,341.910004,343.130005,340.829987,341.394989,6537197,0.0,0.0

In [7]:
msft.actions

            Dividends  Stock Splits
Date
1987-09-21       0.00           2.0
1990-04-16       0.00           2.0
1991-06-27       0.00           1.5
1992-06-15       0.00           1.5
1994-05-23       0.00           2.0
...               ...           ...
2020-11-18       0.56           0.0
2021-02-17       0.56           0.0
2021-05-19       0.56           0.0
2021-08-18       0.56           0.0
2021-11-17       0.62           0.0

[81 rows x 2 columns]

In [21]:
tef=data.get_data_yahoo("TEF.MC", start="2000-01-01")

In [25]:
eurusd=data.get_data_yahoo("EURUSD=x", start="2000-01-01")
eurusd

                High       Low      Open     Close  Volume  Adj Close
Date
2003-12-01  1.204007  1.194401  1.203398  1.196501     0.0   1.196501
2003-12-02  1.210903  1.194600  1.196101  1.208897     0.0   1.208897
2003-12-03  1.213003  1.207700  1.209000  1.212298     0.0   1.212298
2003-12-04  1.214403  1.204398  1.212004  1.208094     0.0   1.208094
2003-12-05  1.219096  1.206593  1.207802  1.218695     0.0   1.218695
...              ...       ...       ...       ...     ...        ...
2021-12-24  1.134430  1.130838  1.132464  1.132734     0.0   1.132734
2021-12-27  1.133500  1.130416  1.132387  1.132426     0.0   1.132426
2021-12-28  1.133600  1.129038  1.132978  1.133003     0.0   1.133003
2021-12-29  1.137001  1.127536  1.131337  1.131478     0.0   1.131478
2021-12-30  1.136622  1.130327  1.135460  1.132631     0.0   1.132631

[4690 rows x 6 columns]

In [10]:
dir(msft)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_analysis',
 '_balancesheet',
 '_base_url',
 '_calendar',
 '_cashflow',
 '_download_options',
 '_earnings',
 '_expirations',
 '_financials',
 '_fundamentals',
 '_get_fundamentals',
 '_history',
 '_info',
 '_institutional_holders',
 '_isin',
 '_major_holders',
 '_mutualfund_holders',
 '_news',
 '_options2df',
 '_recommendations',
 '_scrape_url',
 '_shares',
 '_sustainability',
 'actions',
 'analysis',
 'balance_sheet',
 'balancesheet',
 'calendar',
 'cashflow',
 'dividends',
 'earnings',
 'financials',
 'get_actions',
 'get_analysis',
 'get_balance_sheet',
 'get_balancesheet',
 'get_calendar',
 'get_cashflow',
 'get_dividends',
 'get_earnings',
 'get_financials',
 'get_info',
 'get_institutional_holders',
 'get_isin',
 'get_major_holders',
 'get_mutualfund_holders',
 'get_news',
 'get_recommendations',
 'get_shares',
 'get_splits',
 'get_sustainability',
 'history',
 'info',
 'institutional_holders',
 'isin',
 'major_holders',
 'mutualfund_holders',
 'news',
 'option_chain',
 'options',
 'quarterly_balance_sheet',
 'quarterly_balancesheet',
 'quarterly_cashflow',
 'quarterly_earnings',
 'quarterly_financials',
 'recommendations',
 'session',
 'shares',
 'splits',
 'stats',
 'sustainability',
 'ticker']

In [11]:
dir(spy)

['Close',
 'High',
 'Low',
 'Open',
 'T',
 'Volume',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_align_frame',
 '_align_series',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_join_compat',
 '_logical_func',
 '_logical_method',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [20]:
aa=data.get_components_yahoo("EURUSD=x")

ImmediateDeprecationError:
Yahoo Components has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues

In [14]:
spy

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2000-01-03,148.250000,143.875000,148.250000,145.437500,8164300.0,96.854401
2000-01-04,144.062500,139.640625,143.531250,139.750000,8089800.0,93.066818
2000-01-05,141.531250,137.250000,139.937500,140.000000,12177900.0,93.233269
2000-01-06,141.500000,137.750000,139.625000,137.750000,6227200.0,91.734924
2000-01-07,145.750000,140.062500,140.312500,145.750000,8066500.0,97.062508
...,...,...,...,...,...,...
2021-12-23,472.190002,468.640015,468.750000,470.600006,56384300.0,470.600006
2021-12-27,477.309998,472.010010,472.059998,477.260010,56808600.0,477.260010
2021-12-28,478.809998,476.059998,477.720001,476.869995,47274600.0,476.869995
2021-12-29,478.559998,475.920013,476.980011,477.480011,54354300.0,477.480011
2021-12-30,479.000000,477.700012,477.929993,478.135010,16179806.0,478.135010

In [19]:
spy[spy[key>"2021-01-29"]]

NameError: name 'key' is not defined